bill = input("what is the bill?")
tip = input("how much tip u wanna give?12,15,20,24")
actual_tip = int(bill) / (int(tip)* 100)
print(actual_tip)
actual_bill = int(actual_tip) + int(bill)
print(actual_bill)
split = input("in how many people u wanna split it?")
per = int(actual_bill) / int(split)
print(per)
print(f"bill per person is {per}")
